dist: trusty
sudo: false
language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script: vendor/phpunit/phpunit/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)
